# Generated by Django 5.2.7 on 2026-03-09 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0003_twofactorauth_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='schedule_type',
            field=models.CharField(choices=[('odd', 'Odd days (Mon/Wed/Fri)'), ('even', 'Even days (Tue/Thu/Sat)')], default='odd', max_length=10),
        ),
        migrations.CreateModel(
            name='LessonPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_purchased', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_lesson', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lessons_remaining', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('refunded', 'Refunded')], default='completed', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_payments', to='configapp.group')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configapp.admin')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_payments', to='configapp.student')),
            ],
            options={
                'verbose_name': 'Lesson Payment',
                'verbose_name_plural': 'Lesson Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField()),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='configapp.group')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['group', 'lesson_number'],
                'unique_together': {('group', 'lesson_number')},
            },
        ),
    ]
