# Generated by Django 5.2.7 on 2026-04-12 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0004_group_schedule_type_lessonpayment_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('payment', 'Payment'), ('bonus', 'Bonus Added'), ('remove_lesson', 'Lesson Removed'), ('transfer_student', 'Student Transferred'), ('mark_attended', 'Marked Attended'), ('mark_expired', 'Marked Expired')], max_length=20)),
                ('lessons_affected', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configapp.admin')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='configapp.lessonpayment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='configapp.student')),
            ],
            options={
                'verbose_name': 'Action Log',
                'verbose_name_plural': 'Action Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('paid', 'Paid ✅'), ('bonus', 'Bonus ⭐'), ('unpaid', 'Unpaid 🔴'), ('removed', 'Removed ❌'), ('future', 'Future ⬜')], default='future', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_lessons', to='configapp.group')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_lessons', to='configapp.lesson')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_lessons', to='configapp.lessonpayment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_lessons', to='configapp.student')),
            ],
            options={
                'verbose_name': 'Student Lesson',
                'verbose_name_plural': 'Student Lessons',
                'ordering': ['lesson__scheduled_date'],
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
