# Generated by Django 5.2.7 on 2026-06-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0005_actionlog_studentlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
