# Generated by Django 5.2.7 on 2026-06-08 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0007_alter_student_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='configapp.group'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('bonus', 'Bonus Added'), ('remove_lesson', 'Lesson Removed'), ('student_added', 'Student Added'), ('student_removed', 'Student Removed'), ('group_status_changed', 'Group Status Changed'), ('transfer_student', 'Student Transferred'), ('mark_attended', 'Marked Attended'), ('mark_expired', 'Marked Expired')], max_length=30),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='configapp.student'),
        ),
    ]
