# Generated by Django 5.2.7 on 2026-06-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0008_actionlog_group_alter_actionlog_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='lessonpayment',
            name='price_per_lesson',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='lessonpayment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
