# Generated by Django 5.2.7 on 2026-06-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0010_group_end_time_group_start_time_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
